urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, url, include
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('myproject.vehicles.urls')),
    url(r'^', include('myproject.contact.urls')),
    url(r'^', include('myproject.registration.urls')),
    url(r'^administrador/', include(admin.site.urls)),
    url(r'^terminos_y_condiciones/$', direct_to_template, {'template': 'statics/terms.html'}, name='terms'),
    url(r'^politicas_de_privacidad/$', direct_to_template,{'template': 'statics/policies.html'}, name='policies'),
    url(r'^sobre_nosotros/$', direct_to_template, {'template': 'statics/about_us.html'}, name='about_us'),

)

vehicles/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, url, include
from views import *

urlpatterns = patterns('',
    url(r'^$', home, name='home'),
    url(r'^publicar/$', create_vehicle, name="create_vehicle"), 
    url(r'^(?P<object_id>\d+)/([-\w]+)/$', vehicle_detail, name='vehicle_detail'),
    url(r'^(?P<type_vehicle>\d+)/ver/([-\w]+)/$', vehicle_list, name='vehicle_list'),
)

vehicles/models.py
# -*- coding: utf-8 -*-

from choices import *
from stdimage import StdImageField
from django.db import models
from django.contrib.auth.models import User

class CarManager(models.Manager):
    def get_query_set(self):
        return super(CarManager, self).get_query_set().filter(type_vehicle='1')

class MotorcycleManager(models.Manager):
    def get_query_set(self):
        return super(MotorcycleManager, self).get_query_set().filter(type_vehicle='2')

class Vehicle(models.Model):
    user = models.ForeignKey(User)
    type_vehicle = models.CharField(max_length=4, choices=VEHICLES)
    mark = models.CharField(max_length=30)
    model = models.CharField(max_length=30)
    year = models.PositiveIntegerField()
    description = models.TextField()
    location = models.CharField(max_length=4, choices=LOCATIONS)
    price = models.PositiveIntegerField()
    contact = models.CharField(max_length=30)
    image1 = StdImageField(u'Imagen: ', upload_to='./', size=(600, 800), thumbnail_size=(100, 75))
    image2 = StdImageField(upload_to='./', size=(600, 800), thumbnail_size=(100, 75), blank=True)
    image3 = StdImageField(upload_to='./', size=(600, 800), thumbnail_size=(100, 75), blank=True)
    image4 = StdImageField(upload_to='./', size=(600, 800), thumbnail_size=(100, 75), blank=True)

    objects = models.Manager()

    def __unicode__(self):
        return u'%s %s %d' % (self.mark, self.model, self.year)

    class Meta:
        ordering = ('-id',)
        verbose_name = u'Automotor'
        verbose_name_plural = u'Automotores'

vehicles/forms.py
# -*- coding: utf-8 -*-

from choices import *
from django import forms
from models import Vehicle

class VehicleForm(forms.ModelForm):
    type_vehicle = forms.ChoiceField(
        label=u'Categoría :', choices=VEHICLES,
        help_text='Seleccione la categoría de su automotor.',
        error_messages={
            'required': u'Este campo es obligatorio.',
            'invalid_choice': u'Ingrese un opción válida.',
        }
    )
    mark = forms.CharField(
        label=u'Marca : ', max_length=30,
        help_text='Ingrese la marca de su automotor.',
        error_messages={
            'required': u'Este campo es obligatorio.',
            'invalid': u'Ingrese un valor válido.',
            'max_length': u'Este campo recibe como máximo 30 caracteres.'
        }
    )
    model = forms.CharField(
        label=u'Modelo : ', max_length=30,
        help_text='Ingrese el modelo de su automotor.',
        error_messages={
            'required': u'Este campo es obligatorio.',
            'invalid': u'Ingrese un valor válido.',
            'max_length': u'Este campo recibe como máximo 30 caracteres.'
        }
    )
    year = forms.IntegerField(
        label=u'Año : ', min_value=1940, max_value=2013,
        help_text=u'Ingrese el año de su automotor.',
        error_messages={
            'required': u'Este campo es obligatorio.',
            'invalid': u'Ingrese un año válido (solo números).',
            'max_value': u'Ingrese un año menor ó igual que 2013.',
            'min_value': u'Ingrese un año mayor ó igual que 1940.'
        }
    )
    description = forms.CharField(
        label=u'Descripción : ', widget=forms.Textarea,
        help_text='Ingrese una descripcion ó información extra de su automotor.',
        error_messages={
            'invalid': u'Ingrese un comentario válido.',
            'required': u'Este campo es obligatorio.'
        }
    )
    location = forms.ChoiceField(
        label=u'Categoría :', choices=LOCATIONS,
        help_text='Seleccione la localidad de su automotor.',
        error_messages={
            'required': u'Este campo es obligatorio.',
            'invalid_choice': u'Ingrese un opción válida.',
        }
    )
    price = forms.IntegerField(
        label=u'Precio : ', min_value=1, max_value=1000000,
        help_text=u'Ingrese el precio de su automotor.',
        error_messages={
            'required': u'Este campo es obligatorio.',
            'invalid': u'Ingrese un año válido (solo números).',
            'max_value': u'Ingrese un valor menor ó igual que 1000000.',
            'min_value': u'Ingrese un valor mayor ó igual que 1.'
        }
    )
    contact = forms.CharField(
        label=u'Contacto : ', max_length=30,
        help_text='Ingrese su teléfono de contacto.',
        error_messages={
            'required': u'Este campo es obligatorio.',
            'invalid': u'Ingrese un valor válido.',
            'max_length': u'Este campo recibe como máximo 30 caracteres.'
        }
    )


    class Meta:
        model = Vehicle
        exclude = ('user', 'image2', 'image3', 'image4')

vehicles/views.py
# -*- coding: utf-8 -*-

from choices import *
from models import Vehicle
from forms import VehicleForm
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import redirect_to
from django.views.generic import list_detail
from django.views.generic import create_update

def home(request):
    return list_detail.object_list(
        request,
        queryset=Vehicle.objects.all()[:20],
        template_name='vehicles/home.html',
        extra_context={'vehicles': VEHICLES}
    )

@login_required(redirect_field_name='')
def create_vehicle(request):
    if request.method == 'POST':
        form = VehicleForm(request.POST, request.FILES)
        if form.is_valid():
            model = form.save(commit=False)
            model.user = request.user
            model.save()
            return render_to_response('vehicles/success.html', locals(),\
                context_instance=RequestContext(request))
    else:
        form = VehicleForm()
    return render_to_response('vehicles/vehicle_form.html', locals(),\
        context_instance=RequestContext(request))

def vehicle_detail(request, object_id):
    return list_detail.object_detail(
        request,
        object_id=object_id,
        queryset=Vehicle.objects.all()
    )

def vehicle_list(request, type_vehicle):
    queryset = Vehicle.objects.filter(type_vehicle=type_vehicle)
    return list_detail.object_list(
        request,
        queryset=queryset,
        paginate_by=15,
        page=request.GET.get('pagina')
    )

templates/vehicles/home.html
{% extends "base.html" %}

{% block title %}Inicio{% endblock %}

{% block style %}.vehicle { margin-top:15px;padding-top:15px;border-top: 1px dotted #DDD;}.vehicle.first { border-top:0;padding-top:0; }.vehicle_title { background: url(/static/images/line.png) 0 12px no-repeat;font-weight:bold; }.vehicle_title a { background:#FFF;padding-right:5px; }.vehicle_title span { float:right;background:#FFF;padding-left:5px; }.vehicle_image { width:100px; height:75px; }.vehicle_location { color:#888; }input, select, textarea { width:100%;margin-bottom:20px !important; }input[type="submit"] { padding: 5px 20px;color: white;background: #068;border: 1px solid #068;text-shadow: none;margin-bottom:0;width:auto;}{% endblock %}

{% block content %}
<div id="content_left" class="grid_4">
	<h2>Categorias</h2>
	<ul class="submenu">
	{% for id, vehicle in vehicles %}
		<li class="grid_4 omega alpha {% if forloop.first %}first{% endif %}"><a href="{% url vehicle_list id vehicle|slugify %}">{{ vehicle }}</a><span></span></li>
	{% endfor %}
	</ul>
	<div class="clear"></div>
</div>
<div id="content_right" class="grid_12">
	<h2>Últimos Automotores</h2>
	{% if object_list %}
		{% for vehicle in object_list %}
		<div class="vehicle grid_6 {% if forloop.counter|divisibleby:2 %}omega{% else %}alpha{% endif %}{% if forloop.counter <= 2 %} first{% endif %}">
			<div class="grid_2 alpha">
				<a href="{% url vehicle_detail vehicle.id vehicle|slugify %}"><img class="vehicle_image" src="{{ vehicle.image1.thumbnail.url }}" /></a>
		</div>
		<div class="grid_4 omega">
			<p class="vehicle_title">
				<a href="{% url vehicle_detail vehicle.id vehicle|slugify %}">{{ vehicle }}</a>
				<span>${{ vehicle.price }}</span>
			</p>
			<p>{{ vehicle.description|truncatechars:70 }}</p>
			<p class="vehicle_location">{{ vehicle.get_location_display }}</p>
		</div>
	</div>
	{% if forloop.counter|divisibleby:2 %}
	<div class="clear"></div>
	{% endif %}
	{% endfor %}
	{% else %}
	<p style="font-size:20px; text-align:center;padding-top:70px;">Se el Primero en Publicar !!!</p>
	<p style="font-size:20px; text-align:center;padding-top:20px;"><a href="{% url create_vehicle %}">!!! Publicar GRATIS !!!</a></p>
	{% endif %}
	<h2 style="margin:10px 0;">Seguinos en Facebook</h2>
	<fb:like-box href="http://www.facebook.com/SanLuisAutomotores" width="700" show_faces="true" border_color="#FFF" stream="false" header="false"></fb:like-box>
</div>
<div class="clear"></div>
{% endblock %}

templates/vehicles/home1.html
{% extends "base.html" %}

{% block title %}Inicio{% endblock %}

{% block style %}.vehicle { margin-top:15px;padding-top:15px;border-top: 1px dotted #DDD;}.vehicle.first { border-top:0;padding-top:0; }.vehicle_title { background: url(/static/images/line.png) 0 12px no-repeat;font-weight:bold; }.vehicle_title a { background:#FFF;padding-right:5px; }.vehicle_title span { float:right;background:#FFF;padding-left:5px; }.vehicle_image { width:100px; height:75px; }.vehicle_location { color:#888; }input, select, textarea { width:100%;margin-bottom:20px !important; }input[type="submit"] { padding: 5px 20px;color: white;background: #068;border: 1px solid #068;text-shadow: none;margin-bottom:0;width:auto;}{% endblock %}

{% block content %}
<div id="content_left" class="grid_4">
	<h2>Categorias</h2>
	<ul class="submenu">
	{% for id, vehicle in vehicles %}
		<li class="grid_4 omega alpha {% if forloop.first %}first{% endif %}"><a href="{% url vehicle_list id vehicle|slugify %}">{{ vehicle }}</a><span></span></li>
	{% endfor %}
	</ul>
	<div class="clear"></div>
</div>
<div id="content_right" class="grid_12">
	<h2>Últimos Automotores</h2>
	{% if object_list %}
		{% for vehicle in object_list %}
		<div class="vehicle grid_6 {% if forloop.counter|divisibleby:2 %}omega{% else %}alpha{% endif %}{% if forloop.counter <= 2 %} first{% endif %}">
			<div class="grid_2 alpha">
				<img class="vehicle_image" src="{{ vehicle.image1.thumbnail.url }}" />
		</div>
		<div class="grid_4 omega">
			<p class="vehicle_title">
				<a href="{% url vehicle_detail vehicle.id vehicle|slugify %}">{{ vehicle }}</a>
				<span>${{ vehicle.price }}</span>
			</p>
			<p>{{ vehicle.description|truncatechars:70 }}</p>
			<p class="vehicle_location">{{ vehicle.get_location_display }}</p>
		</div>
	</div>
	{% if forloop.counter|divisibleby:2 %}
	<div class="clear"></div>
	{% endif %}
	{% endfor %}
	{% else %}
	<p style="font-size:20px; text-align:center;padding-top:70px;">Se el Primero en Publicar !!!</p>
	<p style="font-size:20px; text-align:center;padding-top:20px;"><a href="{% url create_vehicle %}">!!! Publicar GRATIS !!!</a></p>
	{% endif %}
	<h2 style="margin:10px 0;">Seguinos en Facebook</h2>
	<fb:like-box href="http://www.facebook.com/SanLuisAutomotores" width="700" show_faces="true" border_color="#FFF" stream="false" header="false"></fb:like-box>
</div>
<div class="clear"></div>
{% endblock %}

templates/vehicles/success.html
{% extends "base.html" %}

{% block title %}Publicación Exitosa !!!{% endblock %}

{% block content %}
<div id="content_left" class="grid_12">
	<h2>Publicación Exitosa !!!</h2>
	<br/>
	<p>Tu publicación se realizó con éxito.</p>
	<br/>
   <a href="{% url vehicle_detail model.id model|slugify %}">Click para visualizarlo.</a>
</div>

<div id="content_right" class="grid_4">
</div>
<div class="clear"></div>
{% endblock %}

templates/vehicles/vehicle_detail.html
{% extends "base.html" %}

{% block title %}{{ object }}{% endblock %}

{% block style %}#InfoVehicle p { padding-bottom:5px;margin-bottom:5px;border-bottom:1px dotted #DDD;}{% endblock %}

{% block content %}
<div id="content_left" class="grid_16">
	<h2><a href="{% url home %}" title="Inicio">Inicio</a> > <a href="{% url vehicle_list object.type_vehicle object.get_type_vehicle_display|slugify %}" title="{{ object.get_type_vehicle_display }}">{{ object.get_type_vehicle_display }}</a> > {{ object }}<span class="right text_center" title="Precio">${{ object.price }}</span></h2>
	<div class="grid_8 alpha" style="padding-top:20px;">
		<div>
			<a href="{{ object.image1.url }}" id="jqzoom" rel='gal1'>
				<img style="padding-bottom:20px;" class="grid_8 alpha" src="{{ object.image1.url }}" />
			</a>
		</div>
	</div>
	<div id="InfoVehicle" class="grid_8 omega" style="padding-top:20px;">
		<div class="grid_8 alpha"><p><b>Por : </b>{{ object.user.username }}</p></div>
		<div class="grid_8 alpha"><p><b>Localidad : </b>{{ object.get_location_display }}</p></div>
		<div class="grid_8 alpha"><p><b>Tel. de Contacto : </b>{{ object.contact }}</p></div>
		<div class="grid_8 alpha"><p><b>Descripción : </b>{{ object.description }}</p></div>
		<div class="grid_8 alpha" style="padding:15px 0;">
			<div style="float:left;width:100px;"><g:plusone href="http://www.sanluisautomotores.com{% url vehicle_detail object.id object|slugify %}"></g:plusone></div>
			<div style="float:left;width:120px;"><a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.sanluisautomotores.com{% url vehicle_detail object.id object|slugify %}" data-lang="es">Twittear</a></div>
			<div style="float:left;width:110px;"><fb:like href="http://www.sanluisautomotores.com{% url vehicle_detail object.id object|slugify %}" send="false" layout="button_count" width="100" show_faces="false"></fb:like></div>
		</div>
	</div>
	<fb:comments href="http://www.sanluisautomotores.com{% url vehicle_detail object.id object|slugify %}" num_posts="4" width="460"></fb:comments>
	<div class="clear"></div>
</div>
<link rel="stylesheet" href="{{ STATIC_URL }}js/css/jquery.jqzoom.css" />
<script src="{{ STATIC_URL }}js/jquery.jqzoom-core-pack.js"></script>
<script type="text/javascript">
$(document).ready(function() {
	$('#jqzoom').jqzoom({
            zoomType: 'standard',
            lens:true,
            preloadImages: false,
            alwaysOn:false,
				zoomWidth: 460,
            zoomHeight: 345, 
				title: false,
        });
});
</script>
<script type="text/javascript">window.___gcfg = {lang: 'es'};(function() {var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;po.src = 'https://apis.google.com/js/plusone.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);})();</script>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
{% endblock %}

templates/vehicles/vehicle_form.html
{% extends "base.html" %}

{% block title %}Publicar{% endblock %}

{% block content %}
<div id="content_left" class="grid_10">
	<h2>Publicar</h2>
	<form id="form_admin" enctype="multipart/form-data" method="POST" action=".">
		{% csrf_token %}
		{% include "form.html" %}
		<div class="prefix_2">
			<input type="submit" value="Publicar">
		</div>
		<div class="clear"></div>
	</form>
</div>

<div id="content_right" class="grid_6">
</div>
<div class="clear"></div>
{% endblock %}

templates/vehicles/vehicle_list.html
{% extends "base.html" %}

{% block title %}{{ object_list.0.get_type_vehicle_display }}{% endblock %}

{% block style %}.vehicle_title { background: url(/static/images/line.png) 0 12px no-repeat;font-weight:bold; padding-bottom:3px;}.vehicle_title a { background:#FFF;padding-right:5px; }.vehicle_title span { float:right;background:#FFF;padding-left:5px; }.vehicle_image { width:100px; height:75px; }.vehicle_location { color:#888; padding-top: 3px;}#paginator{text-align:center;padding-top:20px;}#paginator a{padding:0 10px;}{% endblock %}

{% block content %}
{% if object_list %}
<div id="content_left" class="grid_11">
	<h2><a href="{% url home %}">Inicio</a> > {{ object_list.0.get_type_vehicle_display }}</h2>
	<div id="list">
	{% for vehicle in object_list %}
		<div style="margin-top:10px;padding-bottom:10px;border-bottom: 1px dotted #DDD;">
			<div class="grid_2 alpha">
				<img style="width:100px;" src="{{ vehicle.image1.thumbnail.url }}" />
			</div>
			<div class="grid_9 omega">
				<p class="vehicle_title"><a href="{% url vehicle_detail vehicle.id vehicle|slugify %}">{{ vehicle }}</a><span>${{ vehicle.price }}</span></p>
				<p>{{ vehicle.description|truncatechars:160 }}</p>
				<p class="vehicle_location">{{ vehicle.get_location_display }}</p>
			</div>
			<div class="clear"></div>
		</div>
	{% endfor %}
		<p id="paginator">
			{% if page_obj.has_previous %}
			<a href="?pagina={{ page_obj.previous_page_number }}">Anterior</a>
			{% endif %}
			{% if page_obj.has_previous and page_obj.has_next %}
			|
			{% endif %}
			{% if page_obj.has_next %}
			<a href="?pagina={{ page_obj.next_page_number }}">Siguiente</a>
			{% endif %}
		</p>
	</div>
</div>
<div id="content_right" class="grid_5">
</div>
<div class="clear"></div>
{% else %}
<div class="grid_16">
   <p style="font-size:20px; text-align:center;padding-top:20px;">Se el Primero en Publicar !!!</p>
   <p style="font-size:20px; text-align:center;padding-top:20px;"><a href="{% url create_vehicle %}">!!! Publicar GRATIS !!!</a></p>
</div>
{% endif %}

{% endblock %}